# Generated by Django 4.1.3 on 2022-11-14 01:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_alter_clientaddres_client_delete_client'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='category',
            new_name='name',
        ),
    ]
